[2025-03-23T19:33:01.533-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T19:33:01.546-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-23T20:32:33-04:00 [queued]>
[2025-03-23T19:33:01.551-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-23T20:32:33-04:00 [queued]>
[2025-03-23T19:33:01.552-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-23T19:33:01.571-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_formateo> on 2025-03-24 00:32:33+00:00
[2025-03-23T19:33:01.579-0500] {standard_task_runner.py:72} INFO - Started process 85807 to run task
[2025-03-23T19:33:01.581-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl', 'tarea_formateo', 'manual__2025-03-23T20:32:33-04:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp70x16fk9']
[2025-03-23T19:33:01.582-0500] {standard_task_runner.py:105} INFO - Job 33: Subtask tarea_formateo
[2025-03-23T19:33:01.614-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl.tarea_formateo manual__2025-03-23T20:32:33-04:00 [running]> on host luis-GF65
[2025-03-23T19:33:01.688-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl' AIRFLOW_CTX_TASK_ID='tarea_formateo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T00:32:33+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T20:32:33-04:00'
[2025-03-23T19:33:01.689-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-23T19:33:01.853-0500] {formateo.py:26} INFO - Cargando 359 datos desde data/json/data_json_20250323_193238.json (local)
[2025-03-23T19:33:01.915-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-23T19:33:01.918-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-23T19:33:01.919-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl, task_id=tarea_formateo, run_id=manual__2025-03-23T20:32:33-04:00, execution_date=20250324T003233, start_date=20250324T003301, end_date=20250324T003301
[2025-03-23T19:33:01.993-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T19:33:02.011-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-23T19:33:02.021-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
